### ISSUE TITLE
Truncated Message Handling

### ISSUE THREAD

**Issue by andrewtj** [fcambus/rrda#11]
If the TC bit is set `dns.Exchange()` will return `dns.ErrTruncated` which is not caught in [resolve()](https://github.com/fcambus/rrda/blob/2bd46e785603e8df9c8328f1e444d2d91f52b05e/rrda.go#L110-L114). Tested by looking up `_http._tcp.dns-sd.org. IN PTR`.

**Comment by fcambus** [comment]
Indeed, it seems dns.Exchange() behavior was changed a couple months ago.

Thanks for reporting this, it should be fixed now.

**Comment by jmunson** [comment]
It looks like this behavior was reverted in https://github.com/miekg/dns/issues/814

Now rrda fails to build as a result:

../../go/src/github.com/fcambus/rrda/rrda.go:125:19: undefined: dns.ErrTruncated

**Comment by fcambus** [comment]
Indeed, thanks for reporting this, I reverted to the previous behavior.

RRDA should now build again.
