### ISSUE TITLE
NXDOMAIN

### ISSUE THREAD

**Issue by indolering** [fcambus/rrda#12]
I'm getting an NX error when contacting `https://api.statdns.com/`, is this part of the shutdown?

It would be nice if you would allow queries for `statdns.net`, it's useful for debugging.

**Comment by fcambus** [comment]
Indeed, the free public API has been discontinued and the statdns.net zone too.

**Comment by indolering** [comment]
@fcambus Is it too late to keep statdns.net zone open?  I'm working on the IETF DNS JSON spec and was hoping to create a JSON DNS comparison zoo....

**Comment by fcambus** [comment]
I currently have no plans to put the statdns.net zone back online. One of the reason I put it offline is the [DNS workbench](https://workbench.sidnlabs.nl/) project, which offers a much better alternative :-)

The zone served there has more RR types and it is served by several different implementations.

**Comment by indolering** [comment]
Thank you!
