### ISSUE TITLE
Allow multiple querytype

### ISSUE THREAD

**Issue by soullivaneuh** [fcambus/rrda#13]
# Goal

Currently, we can request only one query type at a time. It would be useful to allow multiple query type at once. something like:

```
https://rrda.domain.com/8.8.8.8:53/free.fr/A,AAAA,NS
```

# Why

We are using RRDA as an internal service to be used by other applications.

On the current case, we want to replace the [`dns_get_record`](https://www.php.net/manual/fr/function.dns-get-record.php) php function by it, but we have some calls with multiple record type:

```php
\dns_get_record($hostname, \DNS_A | \DNS_AAAA | \DNS_CNAME | \DNS_MX | \DNS_TXT);
```

With the current implementation of rrda, we have to make 5 HTTP request to get the same information, which is quite heavy.

**Comment by skunkie** [comment]
Maybe you can use ANY: https://rrda.domain.com/8.8.8.8:53/free.fr/ANY ?
