### ISSUE TITLE
Support for id.server query

### ISSUE THREAD

**Issue by lowinger42** [fcambus/rrda#15]
Any chance of implementing the id.server query?

It's very useful to see what anycast node responds to queries.

```
dig @nsu.dnsnode.net id.server txt -c ch +short
"u4.sub"
```

Specified in RFC4892

**Comment by fcambus** [comment]
Sounds useful, yes. I pushed some commits in the 'id' branch to implement this.

Please rebuild RRDA and try: http://127.0.0.1:8080/nsu.dnsnode.net:53/id
