### ISSUE TITLE
RRDA as a package?

### ISSUE THREAD

**Issue by Soullivaneuh** [fcambus/rrda#4]
I'm not a Golang expert, but I think packages can be release.

Could be possible for you?

One `go get rrda` command would be nicer, isn't it? :-)

**Comment by fcambus** [comment]
If you are only interested about the binary, then this should work: `go get github.com/fcambus/rrda`.

**Comment by Soullivaneuh** [comment]
This works like a charm, thanks!

**Comment by Soullivaneuh** [comment]
Just wondering: Can we get a specific version with this method?
