### ISSUE TITLE
Verbose option

### ISSUE THREAD

**Issue by Soullivaneuh** [fcambus/rrda#6]
It would be great to have a verbose option on command line.

With that, rrda application could print each request it receive for example.

Useful for dev env.

**Comment by fcambus** [comment]
That's outside the scope of the tool, logging doesn't belong in the application itself. See here for the rationale : http://www.cambus.net/the-case-for-nginx-in-front-of-application-servers/

**Comment by Soullivaneuh** [comment]
The received request is just a sample. Could be useful to see what exactly the application does for dev env.
