### ISSUE TITLE
Specify DNS servers

### ISSUE THREAD

**Issue by Soullivaneuh** [fcambus/rrda#7]
Option to specify DNS servers on rrda command.

In this case, API urls can be simplified by ometing DNS server data.

**Comment by fcambus** [comment]
Same rationale as #6, there isn't much point in allowing for two types of endpoints semantics, you can achieve the desired outcome using URL rewriting.

RRDA is intended as a foundation to build DNS looking glasses, being able to specify name servers in the URL is the intended behavior.

**Comment by Soullivaneuh** [comment]
> being able to specify name servers in the URL is the intended behavior.

I'm not saying that we have to remove this behavior, but to have two options.

> you can achieve the desired outcome using URL rewriting.

First of all, it's a method and it would be great to have some config samples on the doc.

But url rewriting is not an option for me. Let me explain my concrete case:

I wrote a ready to use rrda app for docker here: https://hub.docker.com/r/dockervan/rrda/

This image is directly listening on the http port via docker-compose. It would be very painful to setup a nginx/apache alternative image in addition just for a single rewrite.

So I understand the DNS specifying behavior, but I still think both url and option setting worth it.
