### ISSUE TITLE
code.google.com/p/go.net/idna: unable to detect version control system for code.google.com

### ISSUE THREAD

**Issue by Soullivaneuh** [fcambus/rrda#9]
I have this build error from short time: https://hub.docker.com/r/dockervan/rrda/builds/buvug4b46sbrj7j7jgahta6/

Non existent package? Deprecated install method?

**Comment by fcambus** [comment]
This is fixed in 2bd46e785603e8df9c8328f1e444d2d91f52b05e, code.google.com is now permanently down since a week or so.

Thanks for reporting this.
